export enum ERequestFormControls {
  firstName = 'firstName',
  lastName = 'lastName',
  phoneNumber = 'phoneNumber',
  email = 'email',
  userCountry = 'userCountry',
  userCity = 'userCity',
  userInfo = 'userInfo',
  userUnits = 'userUnits',
  unitStatus = 'unitStatus',
  rentType = 'rentType',
  unitCountry = 'unitCountry',
  unitCity = 'unitCity',
  unitDistrict = 'unitDistrict',
  unitInfo = 'unitInfo',
  userRelation = 'userRelation',
  isInvestBefore = 'isInvestBefore',
  callAgreement = 'callAgreement',
  promoCode = 'promoCode',
  extraInfo = 'extraInfo',
}
